CREATE TABLE IF NOT EXISTS D_SYS_USER (
    ID BIGINT PRIMARY KEY NOT NULL,
    NAME VARCHAR(64) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    ENABLED INT NOT NULL DEFAULT 1,
    LAST_LOGIN TIMESTAMP NULL
);

COMMENT ON TABLE D_SYS_USER IS 'Users';
COMMENT ON COLUMN D_SYS_USER.ID IS 'PRIMARY KEY';
COMMENT ON COLUMN D_SYS_USER.NAME IS 'USER NAME';
COMMENT ON COLUMN D_SYS_USER.PASSWORD IS 'USER PASSWORD';
COMMENT ON COLUMN D_SYS_USER.EMAIL IS 'EMAIL';
COMMENT ON COLUMN D_SYS_USER.ENABLED IS 'ENABLED';
COMMENT ON COLUMN D_SYS_USER.LAST_LOGIN IS 'LAST LOGIN';

CREATE TABLE IF NOT EXISTS BP_ORDER (
	ID BIGINT PRIMARY KEY NOT NULL,
    ORDER_NO BIGINT NOT NULL,
    ORDER_DATE TIMESTAMP NOT NULL,
    REC_STATUS CHAR(1) NOT NULL,
	DATE_ADDED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	USER_ADDED BIGINT DEFAULT 1 NOT NULL,
    DATE_MODIFIED TIMESTAMP NULL,
    CONSTRAINT BP_ORDER_UQ UNIQUE (ORDER_NO)
);

COMMENT ON TABLE BP_ORDER IS 'Orders';
COMMENT ON COLUMN BP_ORDER.ID IS 'Primary Key';
COMMENT ON COLUMN BP_ORDER.ORDER_NO IS 'Order number';
COMMENT ON COLUMN BP_ORDER.ORDER_DATE IS 'Order date';
-- ....
COMMENT ON COLUMN BP_ORDER.REC_STATUS IS 'A – Active, D - Deleted';
COMMENT ON COLUMN BP_ORDER.DATE_ADDED IS 'Creation date';
COMMENT ON COLUMN BP_ORDER.USER_ADDED IS 'Creation user';
COMMENT ON COLUMN BP_ORDER.DATE_MODIFIED IS 'Modification date';

--CHECK CONSTRAINTS
ALTER TABLE BP_ORDER ADD CONSTRAINT CC_BP_ORDER_REC_STATUS CHECK (REC_STATUS IN ('A', 'D'));

-- FOREIGN KEY
ALTER TABLE BP_ORDER
    ADD CONSTRAINT FK_BP_ORDER_USER_ADDED FOREIGN KEY (USER_ADDED)
    REFERENCES D_SYS_USER (ID);

