--liquibase formatted sql

--changeset Aleksey Fedorov:1000000000000-1 splitStatements:false
CREATE TABLE IF NOT EXISTS D_SYS_CONFIG (
    ID BIGINT PRIMARY KEY NOT NULL,
	CODE VARCHAR(255) NOT NULL,
	VAL VARCHAR(255) NULL,
	ANNOTATION VARCHAR(255) NOT NULL,
    REC_STATUS CHAR(1) NOT NULL,
    USER_ADDED BIGINT DEFAULT 1 NOT NULL,
	DATE_ADDED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATE_MODIFIED TIMESTAMP NULL,
	CONSTRAINT D_SYS_CONFIG_UQ UNIQUE (CODE)
);

COMMENT ON TABLE D_SYS_CONFIG IS 'System parameters';
COMMENT ON COLUMN D_SYS_CONFIG.ID IS 'primary key';
COMMENT ON COLUMN D_SYS_CONFIG.CODE IS 'code';
COMMENT ON COLUMN D_SYS_CONFIG.VALUE IS 'value';
COMMENT ON COLUMN D_SYS_CONFIG.ANNOTATION IS 'annotation';
COMMENT ON COLUMN D_SYS_CONFIG.REC_STATUS IS 'A – Active, D - Deleted';
COMMENT ON COLUMN D_SYS_CONFIG.USER_ADDED IS 'creation user';
COMMENT ON COLUMN D_SYS_CONFIG.DATE_ADDED IS 'creation date';
COMMENT ON COLUMN D_SYS_CONFIG.DATE_MODIFIED IS 'modification date';

--CHECK CONSTRAINTS
ALTER TABLE D_SYS_CONFIG ADD CONSTRAINT CC_D_SYS_CONFIG_REC_STATUS CHECK (REC_STATUS IN ('A', 'D'));