--liquibase formatted sql

--changeset Aleksey Fedorov:1000000000001-1 splitStatements:false
CREATE TABLE D_PERSON (
    ID BIGINT PRIMARY KEY NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    AGE BIGINT NOT NULL,
    REC_STATUS CHAR(1) NOT NULL,
    CR_DT TIMESTAMP NOT NULL,
    UPD_DT TIMESTAMP NOT NULL
);

COMMENT ON TABLE D_PERSON IS 'Person dictionary';
COMMENT ON COLUMN D_PERSON.ID IS 'Primary Key';
COMMENT ON COLUMN D_PERSON.NAME IS 'Currency description';
COMMENT ON COLUMN D_PERSON.REC_STATUS IS 'A – Active, D - Deleted';
COMMENT ON COLUMN D_PERSON.CR_DT IS 'Creation date';
COMMENT ON COLUMN D_PERSON.UPD_DT IS 'Modification date';