--liquibase formatted sql

--changeset Aleksey Fedorov:1000000000002-1 splitStatements:false
CREATE TABLE IF NOT EXISTS D_SYS_ROLE (
    ID BIGINT PRIMARY KEY NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    CONSTRAINT D_SYS_ROLE_UQ UNIQUE (NAME)
);

COMMENT ON TABLE D_SYS_ROLE IS 'Roles';
COMMENT ON COLUMN D_SYS_ROLE.ID IS 'primary key';
COMMENT ON COLUMN D_SYS_ROLE.NAME IS 'user name';

CREATE TABLE IF NOT EXISTS D_SYS_USER_ROLE (
	ID BIGINT PRIMARY KEY NOT NULL,
	USER_ID BIGINT NOT NULL,
	ROLE_ID BIGINT NOT NULL
);

COMMENT ON TABLE D_SYS_USER_ROLE IS 'Linkes roles and users';
COMMENT ON COLUMN D_SYS_USER_ROLE.ID IS 'primary key';
COMMENT ON COLUMN D_SYS_USER_ROLE.USER_ID IS 'user';
COMMENT ON COLUMN D_SYS_USER_ROLE.ROLE_ID IS 'role';

-- FOREIGN KEY
ALTER TABLE D_SYS_USER_ROLE
    ADD CONSTRAINT FK_D_SYS_USER_ROLE_USER_ID FOREIGN KEY (USER_ID)
    REFERENCES D_SYS_USER (ID);

ALTER TABLE D_SYS_USER_ROLE
    ADD CONSTRAINT FK_D_SYS_USER_ROLE_ROLE_ID FOREIGN KEY (ROLE_ID)
    REFERENCES D_SYS_ROLE (ID);