--liquibase formatted sql

--changeset Aleksey Fedorov:1000000000006-1 splitStatements:false
CREATE TABLE IF NOT EXISTS D_CONTACT_TYPE (
  ID BIGINT PRIMARY KEY NOT NULL,
  ANNOTATION VARCHAR(255) NOT NULL,
  REC_STATUS CHAR(1) NOT NULL,
  USER_ADDED BIGINT DEFAULT 1 NOT NULL,
  DATE_ADDED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  DATE_MODIFIED TIMESTAMP NULL
);

COMMENT ON TABLE D_CONTACT_TYPE IS 'Contact types';
COMMENT ON COLUMN D_CONTACT_TYPE.ID IS 'primary key';
COMMENT ON COLUMN D_CONTACT_TYPE.ANNOTATION IS 'annotation';
COMMENT ON COLUMN D_COUNTRY.REC_STATUS IS 'A – active, D - deleted';
COMMENT ON COLUMN D_COUNTRY.USER_ADDED IS 'modified user';
COMMENT ON COLUMN D_COUNTRY.DATE_ADDED IS 'creation date';
COMMENT ON COLUMN D_COUNTRY.DATE_MODIFIED IS 'modification date';

--CHECK CONSTRAINTS
ALTER TABLE D_CONTACT_TYPE ADD CONSTRAINT CC_D_CONTACT_TYPE_REC_STATUS CHECK (REC_STATUS IN ('A', 'D'));
