--liquibase formatted sql

--changeset Aleksey Fedorov:1000000000007-1 splitStatements:false
CREATE TABLE IF NOT EXISTS D_ORDER_ADVERT (
  ID BIGINT PRIMARY KEY NOT NULL,
  ANNOTATION VARCHAR(255) NOT NULL,
  REC_STATUS CHAR(1) NOT NULL,
  USER_ADDED BIGINT DEFAULT 1 NOT NULL,
  DATE_ADDED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  DATE_MODIFIED TIMESTAMP NULL
);

COMMENT ON TABLE D_ORDER_ADVERT IS 'Order advert types';
COMMENT ON COLUMN D_ORDER_ADVERT.ID IS 'primary key';
COMMENT ON COLUMN D_ORDER_ADVERT.ANNOTATION IS 'annotation';
COMMENT ON COLUMN D_ORDER_ADVERT.REC_STATUS IS 'A – active, D - deleted';
COMMENT ON COLUMN D_ORDER_ADVERT.USER_ADDED IS 'modified user';
COMMENT ON COLUMN D_ORDER_ADVERT.DATE_ADDED IS 'creation date';
COMMENT ON COLUMN D_ORDER_ADVERT.DATE_MODIFIED IS 'modification date';

--CHECK CONSTRAINTS
ALTER TABLE D_ORDER_ADVERT ADD CONSTRAINT CC_D_ORDER_ADVERT_REC_STATUS CHECK (REC_STATUS IN ('A', 'D'));