--liquibase formatted sql

--changeset Aleksey Fedorov:100000000000A-1 splitStatements:false
CREATE TABLE IF NOT EXISTS D_SYS_STORE (
  ID BIGINT PRIMARY KEY NOT NULL,
  CODE VARCHAR(255) NOT NULL,
  ANNOTATION VARCHAR(255) NOT NULL,
  URL VARCHAR(255) NOT NULL,
  REC_STATUS CHAR(1) NOT NULL,
  USER_ADDED BIGINT DEFAULT 1 NOT NULL,
  DATE_ADDED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  DATE_MODIFIED TIMESTAMP NULL
);

COMMENT ON TABLE D_SYS_STORE IS 'Stories';
COMMENT ON COLUMN D_SYS_STORE.ID IS 'primary key';
COMMENT ON COLUMN D_SYS_STORE.CODE IS 'code';
COMMENT ON COLUMN D_SYS_STORE.ANNOTATION IS 'annotation';
COMMENT ON COLUMN D_SYS_STORE.URL IS 'url';
COMMENT ON COLUMN D_SYS_STORE.REC_STATUS IS 'A – active, D - deleted';
COMMENT ON COLUMN D_SYS_STORE.USER_ADDED IS 'modified user';
COMMENT ON COLUMN D_SYS_STORE.DATE_ADDED IS 'creation date';
COMMENT ON COLUMN D_SYS_STORE.DATE_MODIFIED IS 'modification date';

--CHECK CONSTRAINTS
ALTER TABLE D_SYS_STORE ADD CONSTRAINT CC_D_SYS_STORE_REC_STATUS CHECK (REC_STATUS IN ('A', 'D'));