--liquibase formatted sql

--changeset Aleksey Fedorov:1000000000010-1 splitStatements:false
CREATE TABLE IF NOT EXISTS D_ORDER_PAYMENT (
  ID BIGINT PRIMARY KEY NOT NULL,
  ANNOTATION VARCHAR(255) NOT NULL,
  REC_STATUS CHAR(1) NOT NULL,
  USER_ADDED BIGINT DEFAULT 1 NOT NULL,
  DATE_ADDED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  DATE_MODIFIED TIMESTAMP NULL
);

COMMENT ON TABLE D_ORDER_PAYMENT IS 'Order payment types';
COMMENT ON COLUMN D_ORDER_PAYMENT.ID IS 'primary key';
COMMENT ON COLUMN D_ORDER_PAYMENT.ANNOTATION IS 'annotation';
COMMENT ON COLUMN D_ORDER_PAYMENT.REC_STATUS IS 'A – active, D - deleted';
COMMENT ON COLUMN D_ORDER_PAYMENT.USER_ADDED IS 'modified user';
COMMENT ON COLUMN D_ORDER_PAYMENT.DATE_ADDED IS 'creation date';
COMMENT ON COLUMN D_ORDER_PAYMENT.DATE_MODIFIED IS 'modification date';

--CHECK CONSTRAINTS
ALTER TABLE D_ORDER_PAYMENT ADD CONSTRAINT CC_D_ORDER_PAYMENT_REC_STATUS CHECK (REC_STATUS IN ('A', 'D'));