--liquibase formatted sql

--changeset Aleksey Fedorov:1000000000011-1 splitStatements:false
CREATE TABLE IF NOT EXISTS D_ORDER_PAYMENT_DELIVERY (
  ID BIGINT PRIMARY KEY NOT NULL,
  ANNOTATION VARCHAR(255) NOT NULL,
  REC_STATUS CHAR(1) NOT NULL,
  USER_ADDED BIGINT DEFAULT 1 NOT NULL,
  DATE_ADDED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  DATE_MODIFIED TIMESTAMP NULL
);

COMMENT ON TABLE D_ORDER_PAYMENT_DELIVERY IS 'Order payment delivery types';
COMMENT ON COLUMN D_ORDER_PAYMENT_DELIVERY.ID IS 'primary key';
COMMENT ON COLUMN D_ORDER_PAYMENT_DELIVERY.ANNOTATION IS 'annotation';
COMMENT ON COLUMN D_ORDER_PAYMENT_DELIVERY.REC_STATUS IS 'A – active, D - deleted';
COMMENT ON COLUMN D_ORDER_PAYMENT_DELIVERY.USER_ADDED IS 'modified user';
COMMENT ON COLUMN D_ORDER_PAYMENT_DELIVERY.DATE_ADDED IS 'creation date';
COMMENT ON COLUMN D_ORDER_PAYMENT_DELIVERY.DATE_MODIFIED IS 'modification date';

--CHECK CONSTRAINTS
ALTER TABLE D_ORDER_PAYMENT_DELIVERY ADD CONSTRAINT CC_D_ORDER_PAYMENT_DELIVERY_REC_STATUS CHECK (REC_STATUS IN ('A', 'D'));