--liquibase formatted sql

--changeset Aleksey Fedorov:1000000000016-1 splitStatements:false
CREATE TABLE IF NOT EXISTS D_CUSTOMER_TYPE (
	ID BIGINT PRIMARY KEY NOT NULL,
	ANNOTATION VARCHAR(255) NOT NULL,
	REC_STATUS CHAR(1) NOT NULL,
    USER_ADDED BIGINT DEFAULT 1 NOT NULL,
    DATE_ADDED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATE_MODIFIED TIMESTAMP NULL
);

COMMENT ON TABLE D_CUSTOMER_TYPE IS 'Customer types';
COMMENT ON COLUMN D_CUSTOMER_TYPE.ID IS 'primary key';
COMMENT ON COLUMN D_CUSTOMER_TYPE.ANNOTATION IS 'annotation';
-- ....
COMMENT ON COLUMN D_CUSTOMER_TYPE.REC_STATUS IS 'A – active, D - deleted';
COMMENT ON COLUMN D_CUSTOMER_TYPE.USER_ADDED IS 'modified user';
COMMENT ON COLUMN D_CUSTOMER_TYPE.DATE_ADDED IS 'creation date';
COMMENT ON COLUMN D_CUSTOMER_TYPE.DATE_MODIFIED IS 'modification date';

--CHECK CONSTRAINTS
ALTER TABLE D_CUSTOMER_TYPE ADD CONSTRAINT CC_D_CUSTOMER_TYPE_REC_STATUS CHECK (REC_STATUS IN ('A', 'D'));

-- FOREIGN KEY
ALTER TABLE D_CUSTOMER_TYPE
    ADD CONSTRAINT FK_D_CUSTOMER_TYPE_USER_ADDED FOREIGN KEY (USER_ADDED)
    REFERENCES D_SYS_USER (ID);