--liquibase formatted sql

--changeset Aleksey Fedorov:1000000000018-1 splitStatements:false
CREATE TABLE IF NOT EXISTS D_COUNTRY (
  ID BIGINT PRIMARY KEY NOT NULL,
  NAME VARCHAR(128) NOT NULL,
  ISO_CODE_2 VARCHAR(2) NOT NULL,
  ISO_CODE_3 VARCHAR(3) NOT NULL,
  ADDRESS_FORMAT VARCHAR(255) NOT NULL,
  POSTCODE_REQUIRED INT NOT NULL,
  STATUS INT NOT NULL DEFAULT 1,
  REC_STATUS CHAR(1) NOT NULL,
  USER_ADDED BIGINT DEFAULT 1 NOT NULL,
  DATE_ADDED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  DATE_MODIFIED TIMESTAMP NULL
);

COMMENT ON TABLE D_COUNTRY IS 'Countries';
COMMENT ON COLUMN D_COUNTRY.ID IS 'primary key';
COMMENT ON COLUMN D_COUNTRY.NAME IS 'name';
COMMENT ON COLUMN D_COUNTRY.ISO_CODE_2 IS 'country code 2 chars (US, RU, ets)';
COMMENT ON COLUMN D_COUNTRY.ISO_CODE_2 IS 'country code 3 chars (USA, RUR, ets)';
-- ....
COMMENT ON COLUMN D_COUNTRY.REC_STATUS IS 'A – active, D - deleted';
COMMENT ON COLUMN D_COUNTRY.USER_ADDED IS 'modified user';
COMMENT ON COLUMN D_COUNTRY.DATE_ADDED IS 'creation date';
COMMENT ON COLUMN D_COUNTRY.DATE_MODIFIED IS 'modification date';

CREATE UNIQUE INDEX IF NOT EXISTS D_COUNTRY_ISO_CODE_2_UNIQ ON D_COUNTRY(ISO_CODE_2);
CREATE UNIQUE INDEX IF NOT EXISTS D_COUNTRY_ISO_CODE_3_UNIQ ON D_COUNTRY(ISO_CODE_3);

--CHECK CONSTRAINTS
ALTER TABLE D_COUNTRY ADD CONSTRAINT CC_D_COUNTRY_REC_STATUS CHECK (REC_STATUS IN ('A', 'D'));

-- FOREIGN KEY
ALTER TABLE D_COUNTRY
    ADD CONSTRAINT FK_D_COUNTRY_USER_ADDED FOREIGN KEY (USER_ADDED)
    REFERENCES D_SYS_USER (ID);