--liquibase formatted sql

--changeset Aleksey Fedorov:1000000000020-1 splitStatements:false
CREATE TABLE IF NOT EXISTS BP_PERSON (
	ID BIGINT PRIMARY KEY NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NULL,
    MIDDLE_NAME VARCHAR(255) NULL,
    COUNTRY_ISO_CODE_2 CHAR(2) DEFAULT 'RU' NOT NULL,
	PHONE_NUMBER VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(255) NULL,
    REC_STATUS CHAR(1) NOT NULL,
    USER_ADDED BIGINT DEFAULT 1 NOT NULL,
    DATE_ADDED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATE_MODIFIED TIMESTAMP NULL,
    CONSTRAINT D_PERSON_UQ UNIQUE (COUNTRY_ISO_CODE_2, PHONE_NUMBER)
);

COMMENT ON TABLE BP_PERSON IS 'Persons';
COMMENT ON COLUMN BP_PERSON.ID IS 'primary key';
COMMENT ON COLUMN BP_PERSON.FIRST_NAME IS 'first name';
COMMENT ON COLUMN BP_PERSON.LAST_NAME IS 'lirst name';
-- ....
COMMENT ON COLUMN BP_PERSON.REC_STATUS IS 'A – active, D - deleted';
COMMENT ON COLUMN BP_PERSON.USER_ADDED IS 'creation user';
COMMENT ON COLUMN BP_PERSON.DATE_ADDED IS 'creation date';
COMMENT ON COLUMN BP_PERSON.DATE_MODIFIED IS 'modification date';

--CHECK CONSTRAINTS
ALTER TABLE BP_PERSON ADD CONSTRAINT CC_BP_PERSON_REC_STATUS CHECK (REC_STATUS IN ('A', 'D'));

-- FOREIGN KEY
ALTER TABLE BP_PERSON
    ADD CONSTRAINT FK_BP_PERSON_USER_ADDED FOREIGN KEY (USER_ADDED)
    REFERENCES D_SYS_USER (ID);

ALTER TABLE BP_PERSON
    ADD CONSTRAINT FK_D_PERSON_ISO_CODE_2 FOREIGN KEY (COUNTRY_ISO_CODE_2)
    REFERENCES D_COUNTRY (ISO_CODE_2);
