--liquibase formatted sql

--changeset Aleksey Fedorov:1000000000021-1 splitStatements:false
CREATE TABLE IF NOT EXISTS BP_ADDRESS (
  ID BIGINT PRIMARY KEY NOT NULL,
  TYPE_ID BIGINT DEFAULT 1 NOT NULL, /* ТИП */
  COUNTRY_ISO_CODE_2 CHAR(2) DEFAULT 'RU' NOT NULL,
  POST_CODE VARCHAR(6) NULL,
  STREET VARCHAR(255) NULL,
  HOUSE VARCHAR(255) NULL,
  FLAT VARCHAR(255) NULL,
  ADDRESS VARCHAR(255) NULL,
  ANNOTATION VARCHAR(255) NULL,
  REC_STATUS CHAR(1) NOT NULL,
  USER_ADDED BIGINT DEFAULT 1 NOT NULL,
  DATE_ADDED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  DATE_MODIFIED TIMESTAMP NULL
);

COMMENT ON TABLE BP_ADDRESS IS 'Addresses';
COMMENT ON COLUMN BP_ADDRESS.ID IS 'primary key';
COMMENT ON COLUMN BP_ADDRESS.TYPE IS 'type';

-- ....
COMMENT ON COLUMN BP_ADDRESS.REC_STATUS IS 'A – active, D - deleted';
COMMENT ON COLUMN BP_ADDRESS.USER_ADDED IS 'creation user';
COMMENT ON COLUMN BP_ADDRESS.DATE_ADDED IS 'creation date';
COMMENT ON COLUMN BP_ADDRESS.DATE_MODIFIED IS 'modification date';

--CHECK CONSTRAINTS
ALTER TABLE BP_ADDRESS ADD CONSTRAINT CC_BP_ADDRESS_REC_STATUS CHECK (REC_STATUS IN ('A', 'D'));

-- FOREIGN KEY
ALTER TABLE BP_ADDRESS
    ADD CONSTRAINT FK_BP_ADDRESS_USER_ADDED FOREIGN KEY (USER_ADDED)
    REFERENCES D_SYS_USER (ID);

ALTER TABLE BP_ADDRESS
    ADD CONSTRAINT FK_BP_ADDRESS_ISO_CODE_2 FOREIGN KEY (COUNTRY_ISO_CODE_2)
    REFERENCES D_COUNTRY (ISO_CODE_2);

ALTER TABLE BP_ADDRESS
    ADD CONSTRAINT FK_BP_ADDRESS_TYPE FOREIGN KEY (TYPE)
    REFERENCES D_ADDRESS_TYPE (ID);