--liquibase formatted sql

--changeset Aleksey Fedorov:1000000000022-1 splitStatements:false
CREATE TABLE BP_CUSTOMER (
	ID BIGINT PRIMARY KEY NOT NULL,
    TYPE_ID BIGINT DEFAULT 1 NOT NULL,
	PERSON_ID BIGINT NULL,
    STATUS INT DEFAULT 1 NOT NULL,
    REC_STATUS CHAR(1) NOT NULL,
    USER_ADDED BIGINT DEFAULT 1 NOT NULL,
    DATE_ADDED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATE_MODIFIED TIMESTAMP NULL
);

COMMENT ON TABLE BP_CUSTOMER IS 'Customers';
COMMENT ON COLUMN BP_CUSTOMER.ID IS 'primary key';
COMMENT ON COLUMN BP_CUSTOMER.TYPE_ID IS 'type';

-- ....
COMMENT ON COLUMN BP_CUSTOMER.REC_STATUS IS 'A – active, D - deleted';
COMMENT ON COLUMN BP_CUSTOMER.USER_ADDED IS 'creation user';
COMMENT ON COLUMN BP_CUSTOMER.DATE_ADDED IS 'creation date';
COMMENT ON COLUMN BP_CUSTOMER.DATE_MODIFIED IS 'modification date';

--CHECK CONSTRAINTS
ALTER TABLE BP_CUSTOMER ADD CONSTRAINT CC_BP_CUSTOMER_REC_STATUS CHECK (REC_STATUS IN ('A', 'D'));

-- FOREIGN KEY
ALTER TABLE BP_CUSTOMER
    ADD CONSTRAINT FK_BP_CUSTOMER_USER_ADDED FOREIGN KEY (USER_ADDED)
    REFERENCES D_SYS_USER (ID);

ALTER TABLE BP_CUSTOMER
    ADD CONSTRAINT FK_BP_CUSTOMER_PERSON_ID FOREIGN KEY (PERSON_ID)
    REFERENCES BP_PERSON (ID);

ALTER TABLE BP_CUSTOMER
    ADD CONSTRAINT FK_BP_CUSTOMER_TYPE_ID FOREIGN KEY (TYPE)
    REFERENCES D_CUSTOMER_TYPE (ID);
