--liquibase formatted sql

--changeset Aleksey Fedorov:1000000000024-1 splitStatements:false
CREATE TABLE BP_CUSTOMER_COMPANY (
	ID BIGINT PRIMARY KEY NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    COUNTRY_ISO_CODE_2 CHAR(2) DEFAULT 'RU' NOT NULL,
    INN VARCHAR(30) NULL,
    SHORT_NAME VARCHAR(255) NOT NULL,
    LONG_NAME VARCHAR(255) NULL,
    REC_STATUS CHAR(1) NOT NULL,
    USER_ADDED BIGINT DEFAULT 1 NOT NULL,
    DATE_ADDED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATE_MODIFIED TIMESTAMP NULL
);

COMMENT ON TABLE BP_CUSTOMER_COMPANY IS 'Customers companies';
COMMENT ON COLUMN BP_CUSTOMER_COMPANY.ID IS 'primary key';
-- ....
COMMENT ON COLUMN BP_CUSTOMER_COMPANY.REC_STATUS IS 'A – active, D - deleted';
COMMENT ON COLUMN BP_CUSTOMER_COMPANY.USER_ADDED IS 'creation user';
COMMENT ON COLUMN BP_CUSTOMER_COMPANY.DATE_ADDED IS 'creation date';
COMMENT ON COLUMN BP_CUSTOMER_COMPANY.DATE_MODIFIED IS 'modification date';

--CHECK CONSTRAINTS
ALTER TABLE BP_CUSTOMER_COMPANY ADD CONSTRAINT CC_BP_CUSTOMER_REC_STATUS CHECK (REC_STATUS IN ('A', 'D'));

-- FOREIGN KEY
ALTER TABLE BP_CUSTOMER_COMPANY
    ADD CONSTRAINT FK_BP_CUSTOMER_COMPANY_USER_ADDED FOREIGN KEY (USER_ADDED)
    REFERENCES D_SYS_USER (ID);

ALTER TABLE BP_CUSTOMER_COMPANY
    ADD CONSTRAINT FK_BP_CUSTOMER_COMPANY_ID FOREIGN KEY (CUSTOMER_ID)
    REFERENCES BP_CUSTOMER (ID);

ALTER TABLE BP_CUSTOMER_COMPANY
    ADD CONSTRAINT FK_BP_CUSTOMER_COMPANY_ISO_CODE_2 FOREIGN KEY (COUNTRY_ISO_CODE_2)
    REFERENCES D_COUNTRY (ISO_CODE_2);
