--liquibase formatted sql

--changeset Aleksey Fedorov:1000000000025-1 splitStatements:false
CREATE TABLE BP_CUSTOMER_CONTACT (
    TYPE_ID BIGINT DEFAULT 1 NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    PERSON_ID BIGINT NOT NULL,
    CONSTRAINT BP_CUSTOMER_CONTACT_UQ UNIQUE (CUSTOMER_ID, PERSON_ID)
);

COMMENT ON TABLE BP_CUSTOMER_CONTACT IS 'Customers contacts';
COMMENT ON COLUMN BP_CUSTOMER_CONTACT.TYPE_ID IS 'type';
COMMENT ON COLUMN BP_CUSTOMER_CONTACT.CUSTOMER_ID IS 'customer';
COMMENT ON COLUMN BP_CUSTOMER_CONTACT.PERSON_ID IS 'person';

ALTER TABLE BP_CUSTOMER_CONTACT
    ADD CONSTRAINT FK_BP_CUSTOMER_CONTACT_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID)
    REFERENCES BP_CUSTOMER (ID);

ALTER TABLE BP_CUSTOMER_CONTACT
    ADD CONSTRAINT FK_BP_CUSTOMER_CONTACT_PERSON_ID FOREIGN KEY (PERSON_ID)
    REFERENCES BP_PERSON (ID);

ALTER TABLE BP_CUSTOMER_CONTACT
    ADD CONSTRAINT FK_BP_CUSTOMER_CONTACT_TYPE_ID FOREIGN KEY (TYPE_ID)
    REFERENCES D_CONTACT_TYPE (ID);
