--liquibase formatted sql

--changeset Aleksey Fedorov:1000000000041-1 splitStatements:false
CREATE TABLE IF NOT EXISTS BP_ORDER (
	ID BIGINT PRIMARY KEY NOT NULL,
    ORDER_NUM BIGINT NOT NULL,
    ORDER_DATE TIMESTAMP NOT NULL,
    ORDER_TYPE_ID BIGINT DEFAULT 1 NOT NULL,
    SOURCE_TYPE_ID BIGINT DEFAULT 4 NOT NULL,
	ADVERT_TYPE_ID BIGINT DEFAULT 1 NOT NULL,
    PAYMENT_TYPE_ID BIGINT DEFAULT 5 NOT NULL,
    STORE_ID BIGINT DEFAULT 1 NOT NULL,
    CATEGORY_PRODUCT_ID BIGINT DEFAULT 0 NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    AMOUNT_TOTAL NUMERIC(15,4) DEFAULT 0 NOT NULL,
	AMOUNT_TOTAL_WITH_DELIVERY NUMERIC(15,4) DEFAULT 0 NOT NULL,
	AMOUNT_BILL NUMERIC(15,4) DEFAULT 0 NOT NULL,
	AMOUNT_SUPPLIER NUMERIC(15,4) DEFAULT 0 NOT NULL,
	AMOUNT_MARGIN NUMERIC(15,4) DEFAULT 0 NOT NULL,
	AMOUNT_POSTPAY NUMERIC(15,4) DEFAULT 0 NOT NULL,
	ANNOTATION VARCHAR(255) NULL,
    STATUS INT NOT NULL,
    STATUS_EMAIL INT DEFAULT 0 NOT NULL,
    OFFER_COUNT_DAY INT DEFAULT 0 NOT NULL,
    REC_STATUS CHAR(1) NOT NULL,
    USER_ADDED BIGINT DEFAULT 1 NOT NULL,
	DATE_ADDED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATE_MODIFIED TIMESTAMP NULL,
    CONSTRAINT BP_ORDER_UQ UNIQUE (ORDER_NUM)
);

COMMENT ON TABLE BP_ORDER IS 'Orders';
COMMENT ON COLUMN BP_ORDER.ID IS 'primary key';
COMMENT ON COLUMN BP_ORDER.ORDER_NUM IS 'order number';
COMMENT ON COLUMN BP_ORDER.ORDER_DATE IS 'order date';
-- ....
COMMENT ON COLUMN BP_ORDER.REC_STATUS IS 'A – Active, D - Deleted';
COMMENT ON COLUMN BP_ORDER.USER_ADDED IS 'creation user';
COMMENT ON COLUMN BP_ORDER.DATE_ADDED IS 'creation date';
COMMENT ON COLUMN BP_ORDER.DATE_MODIFIED IS 'modification date';

--CHECK CONSTRAINTS
ALTER TABLE BP_ORDER ADD CONSTRAINT CC_BP_ORDER_REC_STATUS CHECK (REC_STATUS IN ('A', 'D'));

-- FOREIGN KEY
ALTER TABLE BP_ORDER
    ADD CONSTRAINT FK_BP_ORDER_USER_ADDED FOREIGN KEY (USER_ADDED)
    REFERENCES D_SYS_USER (ID);

ALTER TABLE BP_ORDER
    ADD CONSTRAINT FK_BP_ORDER_TYPE_ID FOREIGN KEY (ORDER_TYPE)
    REFERENCES D_ORDER_TYPE (ID);

ALTER TABLE BP_ORDER
    ADD CONSTRAINT FK_BP_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID)
    REFERENCES BP_CUSTOMER (ID);