--liquibase formatted sql

--changeset Aleksey Fedorov:1000000000056-1 splitStatements:false
CREATE TABLE IF NOT EXISTS D_CURRENCY (
  ID BIGINT PRIMARY KEY NOT NULL,
  CODE VARCHAR(16) NOT NULL,
  NAME VARCHAR(64) NOT NULL,
  AMOUNT_SCALE BIGINT,
  REC_STATUS CHAR(1) NOT NULL,
  CR_DT TIMESTAMP NOT NULL,
  UPD_DT TIMESTAMP NOT NULL);

COMMENT ON TABLE D_CURRENCY IS 'Currencies dictionary';
COMMENT ON COLUMN D_CURRENCY.ID IS 'Primary Key';
COMMENT ON COLUMN D_CURRENCY.CODE IS 'ISO currency code';
COMMENT ON COLUMN D_CURRENCY.NAME IS 'Currency description';
COMMENT ON COLUMN D_CURRENCY.AMOUNT_SCALE IS 'Amount number of decimal places (ISO)';
COMMENT ON COLUMN D_CURRENCY.REC_STATUS IS 'A – Active, D - Deleted';
COMMENT ON COLUMN D_CURRENCY.CR_DT IS 'Creation date';
COMMENT ON COLUMN D_CURRENCY.UPD_DT IS 'Modification date';

--CHECK CONSTRAINTS
ALTER TABLE D_CURRENCY ADD CONSTRAINT CC_CUR_REC_STATUS CHECK (REC_STATUS IN ('A', 'D'));