--liquibase formatted sql

--changeset Aleksey Fedorov:1000000000091-1 splitStatements:false
CREATE TABLE IF NOT EXISTS D_USER_QUERY (
	ID BIGINT PRIMARY KEY NOT NULL,
    USER_ID BIGINT NOT NULL,
    SHELF VARCHAR(30) NOT NULL,
	CODE VARCHAR(255) NOT NULL,
	VAL VARCHAR(255) NULL,
    CONSTRAINT D_USER_QUERY_UQ UNIQUE (USER_ID, SHELF, CODE)
);

COMMENT ON TABLE D_USER_QUERY IS 'Custom users settings';
COMMENT ON COLUMN D_USER_QUERY.ID IS 'primary key';
COMMENT ON COLUMN D_USER_QUERY.USER_ID IS 'user';
COMMENT ON COLUMN D_USER_QUERY.SHELF IS 'group query for settings';
COMMENT ON COLUMN D_USER_QUERY.CODE IS 'code';
COMMENT ON COLUMN D_USER_QUERY.VAL IS 'value';

-- FOREIGN KEY
ALTER TABLE D_USER_QUERY
    ADD CONSTRAINT FK_D_USER_QUERY_USER_ID FOREIGN KEY (USER_ID)
    REFERENCES D_SYS_USER (ID);



